language: node_js
sudo: false
node_js:
- 4
- 6
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: lr6m8HCF9RGLHee9WzPM5/3v54Rut081UZyfa8ZtbLoQZWZ/l8tU7NVicmY6qHDs9p/FiRHwOsxRlEdk1Y7eObUqzWnwOmC4liZ0SlUuS0JpOoH5fGsF1kzOjOX+1PHyK7Cg8fwhI8VgRpp/aXa8LErQdQ77UasdRGn6/0Z9jb0iPP7vjBrK/v6mHHDxoDDLbhc0UnGrZJb2kawKVx+6vOWfc1CwRGaep/TG7R1RDzY5bc3wXI4av4zxvTiQ0T2Db7PHtHyw9rb8oA85fFWCbJBDRibiAE3D+9q2T60Exwfi0VGIlBmLP/WXmguw6phLvXoIUkXZAtmK7bkstdmkq2/uBl1GkOMLGID61Z9JxXHWN5aFLSfS3LOAg7i2viUfcDyq7GcOP4sYGOJAOl2TxFXgW+LtOC0X21pghDIOYHUDtLfHz8IdcRbv6fSoVixkNcW384q6XeA0FJXSGEP2ioeA+wCEssw0EzB04aIIo9B9VVIC6xS3I3T3td1o32cPclbPAa3hmXW2wf/KfKs5OvRlbv3l3zRfHSskBgJ7j8NpkOdRczVeYy1IEWxQ1Vnb/ffyfJAs7rhKDXEcfuImsvmntqAY2qaw/KDfWgX6dXuPL1XxcopDSQO6nXkHcwGQ11L9EuuJjahe1Aw5rfBnAy/xG1P/nInUcPLq8qlzvsk=
  skip_cleanup: true
  on:
    branch: master
    tags: true
