language: node_js
sudo: false
node_js:
- 4
- 6
script:
- chmod 777 ./shell_scripts/run_selenium_ci_tests.sh
- "./shell_scripts/run_selenium_ci_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: dyHC1ROZ/DYtnAPquQ6F9YI7cnA7JoaSoUkUby4B3+WhKeMzcEjy/a1SUBJRvKAht6o4gmAslnMietSVqiLOTFIooaojYDgi8I9OhO+w6gpx/gwQGkumX9Nz2t1h4YoiiddJHs7FFA/+N18qMe5qux1/DHWttdBaMyhdrKbd72himQrhUljEBkO73cLfntm16GZ6GMTNpvOKX4uyeOJGJe/lKXGLr1z8HxfofUDQxIJbdoM1Lct+h2+izF4hCr6j5DY/+25HvdAQXRQSF8QwsQhoQ8qd5iAvLZg+Y6He+uFfYfIyFkU+K8VNMccyjdJ3QOeFuRxJIPoLmQYqBS7Ni6b4O1yCrEBcnZbCSerEAjwbJXE2sGTPwWtiLdg114MD8P+j1kZUZ1Olz/vO203sDGi8+M1yb7mQ5MksCxSSx1WcrjzknIv0C08HoNojF8e/6eUv1dgl33Gi2hrrDwKYDGoRS6ZIjkU6apElBS+p9Uo6gJnD0jfbpL70Ip+V0bsuOcmDOBPkSW8KI7YgrspbgErG/jSQjYQvZlKwjHf5m3E8GIPyjP7rKfx3DBLArgSr5fk8pBDXIGmNxlN3tuaShH8lwuj/AK0Mz6c5ZnK6/28rsqzn9Riz7p8SBgzGU2wS9keOnbxzDRgCTLQk1dQkNnuAVEnH1bdhMRWKWPLNkbw=
  skip_cleanup: true
  on:
    branch: master
    tags: true
